### ISSUE TITLE
Problem on login with new DSM 5.1

### ISSUE THREAD

**Issue by gablau** [zzarbi/synology#11]
Hello, thanks for you code!!!
I have written a small php application that worked great. 
Now with the new DSM 5.1 does not make me do more access!!
The following is a sample debug of login:

Connect Session: DSM
User: admin
Requested Url GET: https://1.1.1.1:4444/webapi/auth.cgi?account=username&passwd=plaipassword&session=DSM&format=sid&api=SYNO.API.Auth&version=2&method=login
Response code: 0
Result: 
Errore di connessione: Connection Error

you're experiencing some problems with the new version 5.1 of dsm ??
Best Regards
Gabriele

**Comment by lucienimmink** [comment]
My certificate is valid but connecting to a secured https didn't work without the SSL bypass.
I need to include the SSL bypass in my project anyway since most home users won't buy a certificate.
