### ISSUE TITLE
class Synology_Abstract (Abstract.php) contains never used private $_errorCodes

### ISSUE THREAD

**Issue by ronaldhoek** [zzarbi/synology#22]
I suspect this is some leftover after you created a seperate file for the errorcodes (Exception.php)

**Comment by zzarbi** [comment]
It's used on line 179 https://github.com/zzarbi/synology/blob/master/src/Synology/Abstract.php#L179

**Comment by ronaldhoek** [comment]
OK, sorry. Missed that one.
By why are you doing this anyway? Because you also have the same codes (except 100) declared in then 'Synology_Exception' exception class...

This would make the use of the $_errorCodes obsolete...
